### ISSUE TITLE
License of nexus-cas-plugin

### ISSUE THREAD

**Issue by ghost** [fcrespel/nexus-cas-plugin#5]
Hi Fabien,

thank you for that great nexus plugin. I would love to use this plugin in our company for our nexus, but there is no license in the repository and our company policies forbid to use software without a license.

Could you please tell me what license applies to the nexus-cas-plugin / add a LICENSE file to the repository?

Thank you!

Felix

**Comment by fcrespel** [comment]
Hello @fbe, you can consider this plugin to be under the [MIT License](https://opensource.org/licenses/MIT). Note that I haven't maintained it for years, so I don't even know if it still works on more recent Nexus versions. Good luck!
